### ISSUE TITLE
Is it documented how to construct a Unified Symbol Resolution (USR)?

### ISSUE THREAD

**Issue by nrnrnr** [ffevotte/clang-tags#22]
I'm indexing a C99 program.  Suppose I want to find all references to, say, a local variable `e` in a function `eval` in a file `evalstack.c`.  How do I construct the appropriate USR for use with `clang-tags grep`?

Is there documentation that can be found on the construction and meaning of valid USRs?

**Comment by ffevotte** [comment]
It's not documented in `clang-tags`, because USRs are always taken from `libclang` itself. It might be documented in `clang` itself, but I doubt it : IIUC the construction pattern of an USR is not part of the API; `clang` only guarantees that generated USRs identify symbols unequivocally.

It's important to note here that constructing unique USRs is a very complicated process. For example, the two `e` symbols in the following snippet need to be identified as two different variables:

``` c
void eval () {
  int e = 0;
  for (int i = 0 ; i<10 ; ++i) {
    int e = 2 * i;
  }
}
```

---

As noted in #21, the way to identify symbols in `clang-tags` is via their source location. If you want to find the USR for a local variable `e` defined at line 42 of file `evalstack.c`, you can call `clang-tags find-def` like so:

```
clang-tags find-def -i evalstack.c 42
```

and parse the first (i.e. most specific) block in the output.
